/* == ENGINE.HPP =========================================================== **
** ######################################################################### **
** ## Mhatxotic Engine          (c) Mhatxotic Design, All Rights Reserved ## **
** ######################################################################### **
** ## This file is automatically generated by build. Changes are lost     ## **
** ## when the engine is rebuilt.                                         ## **
** ######################################################################### **
** ========================================================================= */
#pragma once                           // Only one incursion allowed
/* ------------------------------------------------------------------------- */
#define VER_NAME    "Mhatxotic Engine"                // Name of engine
#define VER_AUTHOR  "Mhatxotic Design"                // Author of engine
#define VER_MAJOR   25                                // Version major (year)
#define VER_MINOR   8                                 // Version minor (month)
#define VER_BUILD   4                                 // Version build (day)
#define VER_REV     13                                // Version rev (build#)
#define VER_STR_NQ  25,8,4,13                         // Version as literal
#define VER_STR     "25.8.4.13"                       // Version as string
#define VER_DATE    "Mon Aug 04 21:34:07 2025 +0100"  // Compilation date
/* == EoF =========================================================== EoF == */
