/* == ENGINE.HPP =========================================================== **
** ######################################################################### **
** ## Mhatxotic Engine          (c) Mhatxotic Design, All Rights Reserved ## **
** ######################################################################### **
** ## This file is automatically generated by build. Changes are lost     ## **
** ## when the engine is rebuilt.                                         ## **
** ######################################################################### **
** ========================================================================= */
#pragma once                           // Only one incursion allowed
/* ------------------------------------------------------------------------- */
#define VER_NAME    "Mhatxotic Engine"                // Name of engine
#define VER_AUTHOR  "Mhatxotic Design"                // Author of engine
#define VER_MAJOR   26                                // Version major (year)
#define VER_MINOR   3                                 // Version minor (month)
#define VER_BUILD   22                                // Version build (day)
#define VER_REV     124                               // Version rev (build#)
#define VER_STR_NQ  26,3,22,124                       // Version as literal
#define VER_STR     "26.3.22.124"                     // Version as string
#define VER_DATE    "Sun Mar 22 22:49:04 2026 +0000"  // Compilation date
/* == EoF =========================================================== EoF == */
